{{- if .Values.enableKeyVault }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "integration-chart-prod.fullname" . }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "integration-chart-prod.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.aksManagedIdentityClientID }}
{{- end }}

