{{- if .Values.enableKeyVault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretRef }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.aksManagedIdentityClientID }}"
    keyvaultName: "{{ .Values.keyVaultName }}"
    tenantId: "{{ .Values.tenantId }}"
    objects: |
      array:
        - |
          objectName: MONGOURI
          objectType: secret
          objectVersion: ""
        - |
          objectName: JWTSECRET
          objectType: secret
          objectVersion: ""
        - |
          objectName: EMAILUSER
          objectType: secret
          objectVersion: ""
        - |
          objectName: EMAILPASS
          objectType: secret
          objectVersion: ""
        - |
          objectName: ENCRYPTIONKEY
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURESTORAGECONNECTIONSTRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: AZURESERVICEBUSCONNECTIONSTRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: REDISCONNECTIONSTRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: EMAILFROMNAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: EMAILFROMADDRESS
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: {{ .Values.secretRef }}
      type: Opaque
      data:
        - objectName: MONGOURI
          key: MONGODB_URI
        - objectName: JWTSECRET
          key: JWT_SECRET
        - objectName: EMAILUSER
          key: EMAIL_USER
        - objectName: EMAILPASS
          key: EMAIL_PASS
        - objectName: ENCRYPTIONKEY
          key: ENCRYPTION_KEY
        - objectName: AZURESTORAGECONNECTIONSTRING
          key: AZURE_STORAGE_CONNECTION_STRING
        - objectName: AZURESERVICEBUSCONNECTIONSTRING
          key: AZURE_SERVICE_BUS_CONNECTION_STRING
        - objectName: REDISCONNECTIONSTRING
          key: REDIS_CONNECTION_STRING
        - objectName: EMAILFROMNAME
          key: EMAIL_FROM_NAME
        - objectName: EMAILFROMADDRESS
          key: EMAIL_FROM_ADDRESS
{{- end }}
