apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: unicx-backend-kv
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "3c1f8df0-170b-4e6b-8270-b69c7c6505c1"
    keyvaultName: "unicxprod-keyvault2"
    tenantId: "411412b8-3a99-4c00-b972-acf45ebfc76e"
    objects: |
      array:
        - |
          objectName: MONGODBURI
          objectType: secret
        - |
          objectName: JWTSECRET
          objectType: secret
        - |
          objectName: JWTREFRESHSECRET
          objectType: secret
        - |
          objectName: ENCRYPTIONKEY
          objectType: secret
        - |
          objectName: EMAILUSER
          objectType: secret
        - |
          objectName: EMAILPASS
          objectType: secret
        - |
          objectName: EMAILHOST
          objectType: secret
        - |
          objectName: EMAILPORT
          objectType: secret
        - |
          objectName: EMAILFROMNAME
          objectType: secret
        - |
          objectName: EMAILFROMADDRESS
          objectType: secret
        - |
          objectName: AZURESTORAGECONNECTIONSTRING
          objectType: secret
        - |
          objectName: AZURESTORAGECONTAINER
          objectType: secret
        - |
          objectName: AZURESERVICEBUSCONNECTIONSTRING
          objectType: secret
        - |
          objectName: AZUREMONITORCONNECTIONSTRING
          objectType: secret
        - |
          objectName: REDISCONNECTIONSTRING
          objectType: secret
        - |
          objectName: FRONTENDURL
          objectType: secret
        - |
          objectName: APPNAME
          objectType: secret
        - |
          objectName: BASEURL
          objectType: secret
        - |
          objectName: CLEANDATABASE
          objectType: secret
        - |
          objectName: SYSTEMADMINEMAIL
          objectType: secret
        - |
          objectName: SYSTEMADMINPASSWORD
          objectType: secret
        - |
          objectName: SYSTEMADMINTEMPPASSWORD
          objectType: secret
        - |
          objectName: SYSTEMADMINFIRSTNAME
          objectType: secret
        - |
          objectName: SYSTEMADMINLASTNAME
          objectType: secret
  secretObjects:
    - secretName: unicx-backend-secrets
      type: Opaque
      data:
        - objectName: MONGODBURI
          key: MONGODB_URI
        - objectName: JWTSECRET
          key: JWT_SECRET
        - objectName: JWTREFRESHSECRET
          key: JWT_REFRESH_SECRET
        - objectName: ENCRYPTIONKEY
          key: ENCRYPTION_KEY
        - objectName: EMAILUSER
          key: EMAIL_USER
        - objectName: EMAILPASS
          key: EMAIL_PASS
        - objectName: EMAILHOST
          key: EMAIL_HOST
        - objectName: EMAILPORT
          key: EMAIL_PORT
        - objectName: EMAILFROMNAME
          key: EMAIL_FROM_NAME
        - objectName: EMAILFROMADDRESS
          key: EMAIL_FROM_ADDRESS
        - objectName: AZURESTORAGECONNECTIONSTRING
          key: AZURE_STORAGE_CONNECTION_STRING
        - objectName: AZURESTORAGECONTAINER
          key: AZURE_STORAGE_CONTAINER
        - objectName: AZURESERVICEBUSCONNECTIONSTRING
          key: AZURE_SERVICE_BUS_CONNECTION_STRING
        - objectName: AZUREMONITORCONNECTIONSTRING
          key: AZURE_MONITOR_CONNECTION_STRING
        - objectName: REDISCONNECTIONSTRING
          key: REDIS_CONNECTION_STRING
        - objectName: FRONTENDURL
          key: FRONTEND_URL
        - objectName: APPNAME
          key: APP_NAME
        - objectName: BASEURL
          key: BASE_URL
        - objectName: CLEANDATABASE
          key: CLEAN_DATABASE
        - objectName: SYSTEMADMINEMAIL
          key: SYSTEM_ADMIN_EMAIL
        - objectName: SYSTEMADMINPASSWORD
          key: SYSTEM_ADMIN_PASSWORD
        - objectName: SYSTEMADMINTEMPPASSWORD
          key: SYSTEM_ADMIN_TEMP_PASSWORD
        - objectName: SYSTEMADMINFIRSTNAME
          key: SYSTEM_ADMIN_FIRST_NAME
        - objectName: SYSTEMADMINLASTNAME
          key: SYSTEM_ADMIN_LAST_NAME